name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GCP SDK
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker with GCP
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/stock-back:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/stock-back:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/stock-back:latest \
          --platform managed \
          --region europe-west-1
          --allow-unauthenticated \
          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }}
